version: '3'
services:
  core:
    image: gubee/interview
    ports:
      - 8080:8080
    environment:
      - DB_HOSTNAME=db-gubee
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=gubee
      - DB_PWD=gubee
    depends_on:
      - db-gubee

  db-gubee:
    image: gubee/interview-postgres-it
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  pg-admin-gubee:
    image: 'dpage/pgadmin4:6'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050
    depends_on:
      - db-gubee